### ISSUE TITLE
is there any method for getting current date as string in specific type?

### ISSUE THREAD

**Issue by javadKarbasian** [dc0d/Roozh#5]
thanks for this useful and precise library. but i could not find any method to getDate which return current date as string. some thing like that... "11/18/2016" --->convert to  "1395/8/28"
also is there any method to roll calendar?
tanx

**Comment by dc0d** [comment]
The core calculations are solid and robust. But to be honest, it wasn't my intention to expand it. I just wanted a repo for a Persian Calendar in different languages. I might do that whenever I find some free time.

Though any PRs would be most welcome!

**Comment by javadKarbasian** [comment]
can i make some enhancement and pull it?

**Comment by dc0d** [comment]
Would be mu honor! Please put it in it's own folder, because some friends use Roozh.js the way it is.

And I must add I would be very happy even if you just copy this code and publish a lib of your own (the algorithm is not mine, but an english mathematician which I've got his permission to use his algorithm; so I would be proud if this lib become of someones help - I like credits, but in this case, I do not care that much for it - and as an example an extension to moment.js or something like that would be great).

If you decided to go with your own repo, please add it's url to readme so people can find it more easily.

**Comment by javadKarbasian** [comment]
Okay thank.
